version: "3.9"
    
services:
 web:
   image: nginx
   volumes:
    - www:/usr/share/nginx/html
   ports:
    - "80:80"
   environment:
    - NGINX_PORT=80

 postgres:
  image: postgres:13.3
  environment:
   POSTGRES_DB: "mydb"
   POSTGRES_USER: "myuser"
   POSTGRES_PASSWORD: "mypass"
  ports:
   - "5432:5432"
  volumes:
   - .:/docker-entrypoint-initdb.d

volumes:
  www: {}
